version: '3.9'

services:
  server:
    image: node:16
    container_name: server
    working_dir: /src/apps/server
    volumes:
      - .:/src
    env_file:
      - .env
    entrypoint: bash -c "yarn --frozen-lockfile --non-interactive --ignore-scripts && yarn start"
    ports:
      - 8080:8080
